nguage: ruby


rvm:
  - 2.2.0

before_script:
  - cp config/database_sample.yml config/database.yml
  - bundle exec rake db:create db:migrate db:seed
  - export BUNDLE_GEMFILE=$PWD/Gemfile

script:
  - bundle exec rake spec

notifications:
  email:
    recipients:
        - pop-lab-xp-2015@googlegroups.com
    on_success: change
    on_failure: always

