default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: 5
  host: localhost

development:
  <<: *default

test:
  <<: *default
  database: pop_test

production:
  <<: *default
  database: pop_production
  username: ospite
  password: <%= ENV['POP_DATABASE_PASSWORD'] %>
